version: "3.7"


services:
  django:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: 
      './run.sh'
    volumes:
      - ./backend/:/backend/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env

  vue:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    command: 
        npm run serve
    volumes:
      - ./client/:/client/
    ports:
      - 8080:8080
    depends_on:
      - db
      - django
    env_file:
      - .env

  db:
    image: postgres:11.2-alpine
    # restart: always
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data/


volumes:
  db_data: