version: "3.7"


services:
  django:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: 
      './run.sh'
    volumes:
      - ./backend/:/backend/
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - .env
    restart: on-failure

  vue:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    command: 
        npm run serve
    volumes:
      - ./client/:/client/
    # ports:
    #   - 8080:8080
    expose:
      - 8080
    depends_on:
      - db
      - django
    env_file:
      - .env
    restart: on-failure

  db:
    image: postgres:11.2-alpine
    restart: on-failure
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data/

  nginx:
    build:
      context: ./nginx/
      dockerfile: ./Dockerfile
    restart: on-failure
    volumes: 
      - ./backend/media/:/usr/share/nginx/media/
      - ./backend/staticfiles/:/usr/share/nginx/static/
    ports:
      - 80:80
    depends_on:
      - django


volumes:
  db_data: