version: "3.7"


services:
  django:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: 
      './run.sh'
    volumes:
      - ./backend/:/backend/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:11.2-alpine
    # restart: always
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data/


volumes:
  db_data: