# Generated by Django 3.1.7 on 2021-03-21 19:55

import beer_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='beer name')),
                ('description', models.TextField(verbose_name='beer description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('mark', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='beer mark')),
                ('price', models.DecimalField(decimal_places=2, help_text='Beer price in UAH', max_digits=5, verbose_name='beer price')),
                ('image', models.ImageField(upload_to=beer_app.models.image_upload_path, verbose_name='beer image')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
