# Generated by Django 3.1.7 on 2021-03-22 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('text', models.TextField()),
                ('beer', models.ForeignKey(help_text='shows for which beer this comment is', on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='beer_app.beer')),
                ('owner', models.ForeignKey(help_text='owner of this mark', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('mark', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='beer mark')),
                ('beer', models.ForeignKey(help_text='shows for which beer this mark is', on_delete=django.db.models.deletion.CASCADE, related_name='user_marks', to='beer_app.beer')),
                ('owner', models.ForeignKey(help_text='owner of this mark', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('owner', 'beer')},
            },
        ),
    ]
